### ISSUE TITLE
Fails with perls < 5.14

### ISSUE THREAD

**Issue by andk** [meis/Test-Spec-Acceptance#1]
As per subject. Best illustration maybe is the matrix: http://matrix.cpantesters.org/?dist=Test-Spec-Acceptance%200.01

Sample fail report:

http://www.cpantesters.org/cpan/report/6f8adb14-61ed-11e8-ae5c-540550c93e1f

Diagnostics:

syntax error at /tmp/loop_over_bdir-2425-GFAulK/Test-Spec-Acceptance-0.01-0/blib/lib/Test/Spec/Acceptance.pm line 3, near "package Test::Spec::Acceptance {

If you want to keep the package block syntax it would be cool if you could predeclare the dependency. That way the FAILS are converted to UNKNOWNS. Details about how to do it are on this page: http://wiki.cpantesters.org/wiki/CPANAuthorNotes

Thanks!

**Comment by meis** [comment]
Thanks @andk!

I don't really need to keep the block syntax for this module. I'll try to fix this later today.

PS: Thanks for all the links, this is my first module published to CPAN and I probably should have done more research.
